# Generated by Django 6.0.6 on 2026-08-31 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('mechanics', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(db_index=True, help_text='Human-readable booking reference e.g., IM-2024-8192', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'Mechanic On The Way'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Scheduled service date and time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when job was marked completed', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Standard service catalog price in INR', max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra parts/labor added during service in INR', max_digits=10)),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, help_text='Total billable amount in INR', max_digits=10)),
                ('service_location', models.CharField(default='Bengaluru Central Service Bay', help_text='Customer address or workshop location', max_length=255)),
                ('customer_notes', models.TextField(blank=True, help_text='Special requests by customer')),
                ('mechanic_notes', models.TextField(blank=True, help_text='Inspection diagnosis and notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='mechanics.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(db_index=True, max_length=30)),
                ('changed_by', models.CharField(default='Operations Desk', help_text='User, Role or System actor performing the state change', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Optional remarks for transition')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_code'], name='bookings_bo_referen_543fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_at'], name='bookings_bo_status_8276e1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at', 'total_amount'], name='bookings_bo_created_d502fd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mechanic', 'status'], name='bookings_bo_mechani_77791c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_1d3d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['to_status'], name='bookings_bo_to_stat_7da2b9_idx'),
        ),
    ]
