# Generated by Django 6.0.6 on 2026-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatushistory',
            options={'ordering': ['created_at', 'id'], 'verbose_name_plural': 'Booking Status Histories'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(db_index=True, help_text='Human-readable booking reference e.g., IM-260901-00140', max_length=25, unique=True),
        ),
    ]
