# Generated by Django 6.0.6 on 2026-08-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['first_name', 'last_name'], name='customers_c_first_n_146a71_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(help_text='e.g., Maruti Suzuki, Hyundai, Tata', max_length=60)),
                ('model', models.CharField(help_text='e.g., Swift, Creta, Nexon', max_length=60)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year e.g., 2022')),
                ('license_plate', models.CharField(db_index=True, help_text='Registration format e.g. KA 01 MJ 5821', max_length=30, unique=True)),
                ('vin', models.CharField(blank=True, max_length=25, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG'), ('HYBRID', 'Hybrid')], default='PETROL', max_length=20)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Odometer reading in km')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_plate'], name='customers_v_license_b85137_idx'), models.Index(fields=['make', 'model'], name='customers_v_make_d8be15_idx')],
            },
        ),
    ]
