# Generated by Django 6.0.6 on 2026-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy / In Service'), ('ON_TRIP', 'On The Way'), ('OFFLINE', 'Offline')], db_index=True, default='AVAILABLE', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=4.8, help_text='Customer satisfaction rating out of 5.00', max_digits=3)),
                ('total_jobs_completed', models.PositiveIntegerField(db_index=True, default=0, help_text='Total verified completed service bookings')),
                ('specialization', models.CharField(default='General Maintenance & Diagnostics', help_text='Primary technical specialty', max_length=120)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('experience_years', models.PositiveIntegerField(default=4)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-rating', '-total_jobs_completed'],
                'indexes': [models.Index(fields=['status'], name='mechanics_m_status_602be6_idx'), models.Index(fields=['rating'], name='mechanics_m_rating_bf8409_idx'), models.Index(fields=['total_jobs_completed'], name='mechanics_m_total_j_b50edd_idx'), models.Index(fields=['first_name', 'last_name'], name='mechanics_m_first_n_c8fde0_idx')],
            },
        ),
    ]
